backend:
  name: github
  repo: cosmetiqueparisien/cosmetiqueparisienne
  branch: main
  app_id: Ov23liQP4Wf5Jb9amCPZ

media_folder: "images"
public_folder: "/images"

collections:
  - name: "produits"
    label: "المنتجات (Les Box & Chocolat)"
    folder: "data/produits"
    create: true
    extension: "json"
    format: "json"
    fields:
      - {label: "اسم المنتج (مثال: Box Cadeau 1)", name: "title", widget: "string"}
      - {label: "السعر (DA)", name: "price", widget: "number"}
      - {label: "الصنف", name: "gender", widget: "select", options: ["homme", "femme", "chocolat"]}
      - {label: "صورة المنتج", name: "image", widget: "image"}