backend:
  name: github
  repo: cosmetiqueparisien/cosmetiqueparisienne
  branch: main
  use_pkce: true
  app_id: Ov23liQP4Wf5Jb9amCPZ

media_folder: "images"
public_folder: "./images"

collections:
  - name: "produits"
    label: "المنتجات"
    folder: "data/produits"
    create: true
    extension: "json"
    format: "json"
    fields:
      - {label: "اسم المنتج", name: "title", widget: "string"}
      - {label: "السعر", name: "price", widget: "number"}
      - {label: "الصنف", name: "gender", widget: "select", options: ["homme", "femme", "chocolat"]}
      - {label: "صورة", name: "image", widget: "image"}