backend:
  name: github
  repo: cosmetiqueparisien/cosmetiqueparisienne
  branch: main
  app_id: Ov23liQP4Wf5Jb9amCPZ

# --- إعدادات المظهر واللغة ---
locale: "fr"
logo_url: "https://cosmetiqueparisien.github.io/cosmetiqueparisienne/logo.png.PNG" 
# ملاحظة: تقدر تبدل background.jpg باسم ملف اللوغو ديالك إذا طلعته في GitHub

media_folder: "images"
public_folder: "/images"

collections:
  - name: "produits"
    label: "Produits (Les Box & Chocolat)"
    folder: "data/produits"
    create: true
    extension: "json"
    format: "json"
    fields:
      - {label: "Nom du produit", name: "title", widget: "string"}
      - {label: "Prix (DA)", name: "price", widget: "number"}
      - {label: "Catégorie", name: "gender", widget: "select", options: ["homme", "femme", "chocolat", "دببة"]}
      - {label: "Image du produit", name: "image", widget: "image"}
